name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - { name: msrv, version: '1.66' }
          - { name: stable, version: stable }
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust (${{ matrix.toolchain.name }})
        uses: actions-rust-lang/setup-rust-toolchain@v1.5.0
        with:
          toolchain: ${{ matrix.toolchain.version }}

      - name: Test
        run: cargo test --all-features
